#!/bin/bash

# Function to close the browser
close_browser() {
    pkill --oldest chrome
}

# Function to reopen the script
reopen_script() {
    /home/labuser/join_teams
}

# Default Teams meeting URL
DEFAULT_URL="https://teams.live.com/meet/9338359540754?p=m4yAfdKRlUMOQVYz"

# Check if the URL argument is provided
if [ $# -eq 0 ]; then
    URL="$DEFAULT_URL"
elif [ $# -eq 1 ]; then
    URL="$1"
else
    echo "Usage: $0 [Teams_URL]"
    exit 1
fi

# Open the Teams URL in the default web browser and maximize the window
xdg-open "$URL"
sleep 5
xdotool search --onlyvisible --class chromium-browser windowfocus key F11

# Wait for Teams to open (adjust sleep duration as needed)
sleep 20

# Define initial coordinates
x=853
y=703

# Click up to 20 times with increments of 2 changes in x and y coordinates
for (( i = 0; i < 20; i++ )); do
    xdotool mousemove --sync $x $y click 1
    x=$((x + 2))
    y=$((y + 2))
    sleep 1  # Adjust sleep duration as needed
done

echo "Clicked 20 times with increments of 2 changes in coordinates."

# Wait for 5 minutes before reopening the script
sleep 120

# Close the browser
close_browser

# Reopen the script
reopen_script
